name: Git Actions Demo

on: [push]

jobs:
  actions_demo:
    runs-on: abuntu-latest # creating a container (virtual machine) that uses abuntu
    
    steps:
    - run: touch file.txt
    - run: cat file.txt 
    - run: echo "hello world"
    - run: echo "this is text!" >> file.txt
    - run: cat file.txt
    - run: ls -a
    - run: pwd
    - run: echo "$USER"


better_action:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - run: chmod +x cool_script.sh
  - run: ./cool_script.sh
  